[build]
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "18.19.1"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' https://ty-walls.b-cdn.net https://www.googletagmanager.com; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://ty-walls.b-cdn.net; connect-src 'self' https://ty-walls.b-cdn.net;"

# Redirect all routes to index.html for SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Enable HTTP/2 Server Push
[[headers]]
for = "/*"
[headers.values]
Link = "</build/q-*.js>; rel=preload; as=script"
